### ISSUE TITLE
How to run crossplane on C/C++?

### ISSUE THREAD

**Issue by Taymindis** [nginxinc/crossplane#55]
I have a program which running on C/C++, I want it to be able to retrieve this config to JSON.

**Comment by aluttik** [comment]
crossplane is a Python program that you can import into other Python code or run via the commandline. If you want to use it from C++, then I suggest you either find a way to run a commandline program and get it’s output in your code, or you embed Python like this: https://docs.python.org/3.6/extending/embedding.html.

Because this is more of a C++/Python problem than a crossplane problem, I’m going to close this issue. Best of luck.
