### ISSUE TITLE
build ignores the -d argument

### ISSUE THREAD

**Issue by rolfen** [nginxinc/crossplane#72]
**Describe the bug**
The documentation for the `build` command describes:
`  -d PATH, --dir PATH   the base directory to build in`
However, in practice, this does not produce the expected effect.

**To Reproduce**
`crossplane parse /etc/nginx/nginx.conf |crossplane build -d /tmp /dev/stdin`

**Expected behavior**
crossplane produces new configuration files inside the `/tmp` directory as instructed by the `-d` option

**Actual behavior**
crossplane tries to overwrite the configuration files in `/etc/nginx`

**Your environment**
 * crossplane 0.5.2
 * Linux 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5 (2019-06-19) x86_64 GNU/Linux

**Comment by aluttik** [comment]
Hi @rolfen, thanks for the issue!

The issue here is because the `-d` option will only apply to the files in the crossplane JSON that use relative paths. If you pipe the parsed config file into the build command, you'll always write to /etc/nginx/nginx.conf because the absolute path is stored in the JSON.

I can see why that'd be confusing. We'll consider editing the help message and README.

**Comment by rolfen** [comment]
Hi!

Oh, OK! Thank you for the prompt clarification, it makes sense.

I am closing the issue, because the issue strictly as described is resolved.

However a note in the documentation would be very welcome.

Feel free to reopen it if you prefer.

**Comment by rolfen** [comment]
I was trying to build config files into a temporary directory so that I can examine them.
To do so, I had to rewrite absolute paths because crossplane would not override them. 
This is how I managed to achieve what I intended:

```
mkdir /tmp/nginx.conf/
crossplane parse /etc/nginx/nginx.conf |sed s:\"/etc/nginx/:\"/tmp/nginx.conf/:g |crossplane build /dev/stdin
```
